version: "3.9"

services:
  db:
    image: postgres:14.1
    env_file:
      - db.env

  rabbitmq:
    image: "rabbitmq:alpine"

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  django:
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - django.env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    restart: on-failure

  celery:
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    command: celery -A src.tasks worker -l info --without-gossip --without-mingle --without-heartbeat
    env_file:
      - celery.env
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    restart: on-failure

  beats:
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    command: celery -A src.tasks beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - celery.env
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    restart: on-failure
